### PR TITLE
dont error when group has no :

### PR DESCRIPTION
**Pull request by maartenkling**

### CODE REVIEW

**Comment by adamcheasley** [comment]
Although this will no longer throw and exception, it appears that a group that does not contain a ':' will not be added to the query. Is this the correct behaviour?

**Comment by davisagli** [comment]
Yes; all workspace-based groups have a colon. The format is [workspace group name]:[workspace UID]

**Comment by maartenkling** [comment]
im having membrane groups and they error when combining them

**Comment by adamcheasley** [comment]
Ah ha, ok. Understood.

**Comment by tisto** [comment]
No activity since 2015. Closing...

**Pull request closed without merging**
