### PR TITLE
Use normal Plone groups

### PR DESCRIPTION
**Pull request by davisagli**
@adamcheasley @mattss Could you take a look at this fairly major change and let me know if it looks like it will cause problems for the Plone intranet project?

The gist of the change is that instead of workspace groups being looked up via a special PAS plugin that does catalog queries, workspace rosters now add people to normal Plone groups. This was motivated by performance (turns out looking up all the workspaces via the catalog can take a while if you have many workspaces, even if things are well cached; whereas with standard Plone groups it's just a single BTree lookup to find a user's groups).

There is an upgrade step to add the groups based on existing rosters.

I've been using this in production on my project for a number of months and the kinks seem to be worked out, but can't hurt to have another review!

### CODE REVIEW

**Comment by mattss** [comment]
The dynamic PAS plugin was one of the key things that attracted us to this package, because it means that Plone's standard groups doesn't start filling up with loads of workspace-specific stuff.

In ploneintranet.workspace, the user groups for a workspace are designed to be specific to that workspace, and most of them don't make sense to be used in any other context. We specific disable the 'IGroupEnumerationPlugin' interface for the PAS plugin, so that these groups are not shown anywhere else in the UI.

We may be able to get around this in a different way, and ploneintranet's UI may change significantly enough from Plone in future that we don't care about the groups appearing in standard Plone UI. We'll have to do a bit further digging to work out the actual fall-out of this change.

**Comment by davisagli** [comment]
Aha, right. In my case it actually was important for the workspace groups to show up sitewide, so that the Sharing tab can be used to share an item with a workspace group even if it's not inside that workspace.

It would be nice to make this configurable. With the approach taken in this PR, I guess that would require patching the groups tool to skip groups whose id includes a colon.

**Comment by mattss** [comment]
Rather than patching, would it be possibly to have a specific custom PAS plugin for the workspace, but one which simply extended the standard plone groups plugin, adding the ability to customise the visibility of those groups?

**Comment by petri** [comment]
@davisagli, what kind of numbers are we talking here- when would you say the catalog queries start becoming an issue? 20 workspaces? 50? 100? 500? I have a possible use case and would appreciate any empirical evidence you may have.

**Comment by davisagli** [comment]
@petri I only have one data point, which is a site with about 25,000 workspaces where the catalog queries were a problem. The problem may have been influenced by other customizations specific to my site. Measure your own use case.

**Comment by pgrunewald** [comment]
Hi David. What is the state of this branch? Is it considered to be stable and will be merged into master? I am afraid we also experience said performance penalty. The catalog queries caused by the catalog-based PAS plugin add up to roughly 15% of the overall computation for a single request.

**Comment by davisagli** [comment]
I consider this branch to be more stable than master; it is the one I've been using in production for a couple years. That was originally because of the performance issues, but I've since continued to fix other issues on this branch.

I'm not actively working on merging it to master. I'd like to but there are a couple blockers which will take some time to solve:
1. Write an upgrade step to remove the PAS plugin and create standard Plone groups for existing workspaces.
2. Make sure that workspace groups do not show up in the Users & Groups control panel or the Add User form.

I would probably be able to do that work sooner if someone is interested in paying me to work on it.

**Comment by adamcheasley** [comment]
I believe that some of the work for point 2 that David mentions may have already gone into the ploneintranet workspace. I could be wrong, but I do recall some conversations around that issue. 
It may be possible to just move that work from ploneintranet into this package.

**Comment by mattss** [comment]
To achieve 2. in ploneintranet we just disable the IGroupEnumerationPlugin part of the collective.workspace pas plugin, which stops them being listed anywhere. This works in PI because all our views are completely custom so we can manually list the groups when required. However I'm not sure that would fit the use case of standard collective.workspace.

https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/setuphandlers.py#L63

**Comment by pgrunewald** [comment]
Indeed. It probably should be configurable in site-setup. Also, reading the commit messages, it could be beneficial to decide, whether to keep or clear the roster after copying a workspace.

We have a fork running of the master branch and integrated workspace groups in the global group management (@@usergroup-groupprefs) allowing easy management. Which probably is obsolete now, since it's running with native groups anyway. Point is, that I feel I could offer some of my time to help out with the missing pieces.

**Comment by malthe** [comment]
@davisagli, instead of asking the catalog for a user's site-wide group memberships (including those from workspaces), why not just walk up the parent chain?

Even with nested workspaces, this should limit the cost of looking up groups given some context.

**Comment by davisagli** [comment]
@malthe In my use case I need to know about membership in workspaces outside the containment chain. The sharing tab and local role adapters are used extensively to grant a workspace group from one part of the site access to content in a different part.

**Comment by davisagli** [comment]
Closed in favor of #19, which takes a similar approach to this branch, but continues to use a separate plugin for workspace groups (and is updated with changes from master).

**Pull request closed without merging**
