### PR TITLE
Datakurre Plone 5

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by ale-rt** [comment]
@datakurre I see here we also have some new features.
What about finishing #31 and than backporting the features to what will be the new master?

**Comment by datakurre** [comment]
@ale-rt It could be enough to cherry pick https://github.com/collective/collective.workspace/commit/7a6f0ff8a8efdf4dd1424fb6ed0cc9470b71931d for the “new feature” and possibly copy Finnish localization from this branch if nothing else is really needed from this.

**Comment by ale-rt** [comment]
Yes, 7a6f0ff is actually a thing I like a lot :)
After #31 is merged I will take care of that!
About finnish translation I will also make a new PR.
Thanks for the moment

**Comment by ale-rt** [comment]
Probably obsoleted by #31

**Pull request closed without merging**
