### PR TITLE
kitconcept buildout.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by ale-rt** [comment]
LOL

**Comment by tisto** [comment]
@ale-rt ? :) I need this to make a release...had to fight a bit with Travis allow_failures...

**Comment by ale-rt** [comment]
I know, is this adding to master that you did not have before?

**Comment by tisto** [comment]
Crap. Just realized I do not have pypi permissions. @davisagli could you grant me (user: timo) permissions on pypi?

**Comment by tisto** [comment]
@ale-rt this PR is basically just infrastructure stuff (buildout, travis, etc.). I also fixed flake8 and black on the way. I thought it would be a quick thing to do at first...took a bit longer and the PR grew a bit bigger than expected. I can make a release as soon as someone grants me pypi permissions.

**Comment by tisto** [comment]
@ale-rt zest.releaser, flake8 config, black (and sanity for myself so I do not have to maintain hundreds of individual configurations).

**Comment by ale-rt** [comment]
Good for the good stuff you added and thanks for that.
But some things are not really done properly ;)

**Comment by tisto** [comment]
@ale-rt you mean in buildout/travis or in code? Please let me know what I can improve! :)

**Comment by ale-rt** [comment]
I am making a PR

**Comment by ale-rt** [comment]
I would also remove https://github.com/collective/collective.workspace/blob/master/plone-4.3.x.cfg and the Makefile...
Sincerely I prefered the much simpler buildout we had before.

**Comment by tisto** [comment]
@ale-rt I am ok with removing plone-4.3.x.cfg but don't take away my Makefile please. This is what keeps me sane switching between JS and Python all the time. The Makefile is just an additional nice-to-have. You can completely ignore it if you don't like it.

**Comment by ale-rt** [comment]
I love Makefiles, but that one just doesn't fit here... anyway I am not going to touch this package anymore today.

**Pull request merged**
