### PR TITLE
getPropertiesForUser: decode workspace title

### PR DESCRIPTION
**Pull request by cillianderoiste**
workspace.context.Title() is a bytestring and group_name is unicode. Decode workspace title so they can be joined.

### CODE REVIEW

**Comment by pysailor** [comment]
@matts I tried to fix the build (see #9). Locally it works (running `bin/test -t workspace.robot 
` passes), but travis still fails. Nevertheless, can you please review this PR since it fixes a real-world bug?

**Comment by mattss** [comment]
@pysailor Looks good - any chance of a test to verify this change?

**Comment by pysailor** [comment]
@mattss Good idea about the test, but that would mean to either 1) write from scratch a suite of tests for users & groups integration and PAS (nothing of the sort exists) or 2) writing a robot-test for it. I'm happy to do 2) but as long as travis can't run them, it won't help much I'm afraid.

**Comment by pysailor** [comment]
@matts ok, scratch that - I have no idea about the package collective.workspace outside of ploneintranet :-) and I don't know how to trigger the PAS case in a test, or on which page/template in Plone `getPropertiesForUser` would get called. 

Since the test coverage is rudimentary for this package, can we get away without a new test?

**Comment by mattss** [comment]
Yep I forgot that we don't have full tests here ;) I'm just trying to get selenium working on travis now.

**Comment by gyst** [comment]
I've built out this branch locally with travis.cfg. Tests pass fine. Restarted Travis job.

**Comment by gyst** [comment]
The tests don't even cover the lines changed by this PR, so the breakage comes from bitrot elsewhere.

**Comment by gyst** [comment]
Looking at the Travis build history, Travis tests for this package have been broken now for a year already and there's been multiple master commits since then. @davisagli How about merging this PR? Note that it has been tested by myself and @pysailor green, it's Travis that is the problem not the code.

**Comment by mattss** [comment]
Agreed that travis tests should be fixed separately. Merging.

**Comment by gyst** [comment]
On 27/08/15 10:50, Matthew Sital-Singh wrote:
> Agreed that travis tests should be fixed separately. Merging.

Can you also cut a pypi release so we get this fix into ploneintranet?

:*CU#
-- 
    Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

    s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by tisto** [comment]
Whoever wants to merge something should fix the build before merging. Otherwise the build will be broken forever and nobody feels responsible. Doing a release on a broken build is also not really acceptable. CI becomes meaningless if we decide to ignore the basic rules. Just my two cents...

**Comment by tisto** [comment]
FYI: I have the same robot failure on my local machine that I see on travis. It's definitely not a travis problem...

I had to pin a few robot dependencies to make the tests run on my machine:

https://github.com/collective/collective.workspace/pull/11

**Comment by gyst** [comment]
On 27/08/15 16:20, Timo Stollenwerk wrote:
> FYI: I have the same robot failure on my local machine that I see on
> travis. It's definitely not a travis problem...
> 
> I had to pin a few robot dependencies to make the tests run on my machine:
> 
> #11 <https://github.com/collective/collective.workspace/pull/11>

It's an environment issue then, because I built travis.cfg in a minimal
sandbox virtual and can run all the tests green no problem.

I'm using the same Ubuntu Docker config I use for all my projects.

It's interesting that your env should have the same failures as Travis
but mine does not. It's possible that it pulls in more modern eggs
because I run "-N" against my global eggs cache.

Can you please send me your 'bin/test' file from your build, so I can
compare egg versions against mine and see if I can solve it that way?

:*CU#
-- 
    Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

    s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Comment by tisto** [comment]
buildout.cfg and travis.cfg use two different versions of buildout.plonetest. I stopped using buildout.plonetest quite a while ago because I constantly ran into those kind of issues...

**Comment by gyst** [comment]
On 28/08/15 09:00, Timo Stollenwerk wrote:
> buildout.cfg and travis.cfg use two different versions of
> buildout.plonetest. I stopped using buildout.plonetest quite a while ago
> because I constantly ran into those kind of issues...

Yes but you said you could reproduce the bugs locally. I'm interested in
your bin/test executable for that since it exactly shows the eggs you're
using.

I don't have the test failures locally, so the difference gives me an
entry point in trying to fix Travis.

:*CU#
-- 
    Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

    s o c i a l   k n o w l e d g e   t e c h n o l o g y

**Pull request merged**
