### PR TITLE
fix_workspace_members: Use list comprehension instead of generator.

### LINKED ISSUE #44: Error in upgrade "Fix the workspace_members indexer"
When trying to run the upgrade step "Fix the workspace_members indexer" I get the error

```
Traceback (most recent call last):
  File "***/eggs/ftw.upgrade-3.0.3-py2.7.egg/ftw/upgrade/jsonapi/plonesite.py", line 196, in _install_upgrades
    *api_ids, propose_deferrable=propose_deferrable)
  File "***/eggs/ftw.upgrade-3.0.3-py2.7.egg/ftw/upgrade/executioner.py", line 62, in install_upgrades_by_api_ids
    return self.install(data)
  File "***/eggs/ftw.upgrade-3.0.3-py2.7.egg/ftw/upgrade/executioner.py", line 48, in install
    self._upgrade_profile(profileid, upgradeids)
  File "***/eggs/ftw.upgrade-3.0.3-py2.7.egg/ftw/upgrade/executioner.py", line 111, in _upgrade_profile
    last_dest_version = self._do_upgrade(profileid, upgradeid) \
  File "***/eggs/ftw.upgrade-3.0.3-py2.7.egg/ftw/upgrade/executioner.py", line 151, in _do_upgrade
    step.doStep(self.portal_setup)
  File "***/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "***/eggs/collective.workspace-3.0b2-py2.7.egg/collective/workspace/setuphandlers.py", line 97, in fix_workspace_members
    for key in keys_to_fix:
  File "***/eggs/collective.workspace-3.0b2-py2.7.egg/collective/workspace/setuphandlers.py", line 96, in &lt;genexpr&gt;
    keys_to_fix = (key for key in index._index if isinstance(key, six.text_type))
RuntimeError: the bucket being iterated changed size
```

My guess is that the generator needs to be consumed to a list before making the changes.

See also #41

### PR DESCRIPTION
**Pull request by reinhardt**
Fixes "RuntimeError: the bucket being iterated changed size"
Fixes #44

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
LGTM and thanks!

**Comment by ale-rt** [comment]
Unluckily the build fails on Python 3. It would be great to fix it before merging

**Comment by reinhardt** [comment]
Travis fails with

> Error: The requirement ('importlib-metadata>=1') is not allowed by your [versions] constraint (0.20)

This doesn't look related to the change.

**Comment by ale-rt** [comment]
Yeah, it is some test setup issue.

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
